/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.kasirapp.view;

import com.mycompany.kasirapp.authentication.Auth;
import com.mycompany.kasirapp.model.Cashier;
import com.mycompany.kasirapp.model.Supermarket;
import com.mycompany.kasirapp.model.Transaksi;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer SPIN
 */
public class companyHistoryPage extends javax.swing.JPanel {
    private JPanel goodsPage,orderPage,settingsPage,index;
    /**
     * Creates new form historyPage
     */
    public companyHistoryPage() {
        initComponents();
        this.setSize(1280, 832);
        notif.setVisible(false);
    }

    public void setGoodsPage(JPanel goodsPage) {
        this.goodsPage = goodsPage;
    }

    public void setOrderPage(JPanel orderPage) {
        this.orderPage = orderPage;
    }

    public void setSettingsPage(JPanel settingsPage) {
        this.settingsPage = settingsPage;
    }
    public void setIndex(JPanel index) {
        this.index = index;
    }
    public void fillTableHistory(){
        Supermarket supermarket = Auth.supermarket;
        List<Transaksi> transaksis = supermarket.hasManyTransaksi();
        Object data[][] = new Object[0][0];
  
        data = new Object[transaksis.size()][5];
        for(int i = 0; i < transaksis.size(); i++){
            data[i][0] = transaksis.get(i).getIdTransaksi();
            data[i][1] = transaksis.get(i).getIdKasir();
            data[i][2] = transaksis.get(i).getQuantity();
            data[i][3] = transaksis.get(i).getTotal();
            data[i][4] = transaksis.get(i).getDate();
        }
        String judul[] = {"Id Transaksi","Id Kasir", "Quantity", "Total", "Date"};
//        JTable a = new JTable(data,judul);
        jTable2.setModel(new DefaultTableModel(data, judul));
        jScrollPane5.setViewportView(jTable2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        notif = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yesbtn = new javax.swing.JButton();
        nobtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        goodsBtn1 = new javax.swing.JButton();
        historyBtn1 = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        registerLabel1 = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notif.setBackground(new java.awt.Color(255, 255, 255));
        notif.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apakah anda ingin keluar?");

        yesbtn.setBackground(new java.awt.Color(33, 146, 255));
        yesbtn.setForeground(new java.awt.Color(255, 255, 255));
        yesbtn.setText("YA");
        yesbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesbtnActionPerformed(evt);
            }
        });

        nobtn.setText("No");
        nobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\danger.png")); // NOI18N

        javax.swing.GroupLayout notifLayout = new javax.swing.GroupLayout(notif);
        notif.setLayout(notifLayout);
        notifLayout.setHorizontalGroup(
            notifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notifLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
            .addGroup(notifLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(yesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notifLayout.setVerticalGroup(
            notifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(notifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 301, 220, 120));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Transaksi", "Id Barang", "Id Kasir", "Quatity", "Total", "Date"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 241, 490, 340));

        jPanel6.setBackground(new java.awt.Color(33, 146, 255));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        goodsBtn1.setBackground(new java.awt.Color(33, 146, 255));
        goodsBtn1.setForeground(new java.awt.Color(255, 255, 255));
        goodsBtn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\goods--outline.png")); // NOI18N
        goodsBtn1.setContentAreaFilled(false);
        goodsBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goodsBtn1.setMargin(new java.awt.Insets(30, 15, 0, 15));
        goodsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodsBtn1ActionPerformed(evt);
            }
        });
        jPanel6.add(goodsBtn1, new java.awt.GridBagConstraints());

        historyBtn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\history--fill.png")); // NOI18N
        historyBtn1.setContentAreaFilled(false);
        historyBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBtn1.setMargin(new java.awt.Insets(30, 15, 0, 15));
        historyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel6.add(historyBtn1, gridBagConstraints);

        settingsBtn.setBackground(new java.awt.Color(245, 245, 245));
        settingsBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\settings.png")); // NOI18N
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.setMargin(new java.awt.Insets(30, 15, 0, 15));
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel6.add(settingsBtn, gridBagConstraints);

        logoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\logout.png")); // NOI18N
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setMargin(new java.awt.Insets(30, 15, 0, 15));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 511, 0);
        jPanel6.add(logoutBtn, gridBagConstraints);

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        registerLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        registerLabel1.setForeground(new java.awt.Color(33, 146, 255));
        registerLabel1.setText("History");
        add(registerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 79, -1, -1));

        registerLabel.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        registerLabel.setText("Barang");
        add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 79, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void historyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtn1ActionPerformed
 
    }//GEN-LAST:event_historyBtn1ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
       notif.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        this.setVisible(false);
        settingsPage.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void goodsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodsBtn1ActionPerformed
        this.setVisible(false);
        goodsPage.setVisible(true);
    }//GEN-LAST:event_goodsBtn1ActionPerformed

    private void yesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.index.setVisible(true);
        this.notif.setVisible(false);
    }//GEN-LAST:event_yesbtnActionPerformed

    private void nobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobtnActionPerformed
        // TODO add your handling code here:
        this.notif.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_nobtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goodsBtn1;
    private javax.swing.JButton historyBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton nobtn;
    private javax.swing.JPanel notif;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel registerLabel1;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JButton yesbtn;
    // End of variables declaration//GEN-END:variables
}
