/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kasirapp.view;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Label;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.awt.Graphics;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import com.mycompany.kasirapp.component.frame;
/**
 *
 * @author Acer SPIN
 */
public class index extends javax.swing.JFrame {

    registerPage registerPage = new registerPage();
    companyLoginPage companyLoginPage = new companyLoginPage();
    goodsPage goodsPage = new goodsPage();
    orderPage orderPage = new orderPage();
    cashierHistoryPage cashierHistoryPage = new cashierHistoryPage();
    companyHistoryPage companyHistoyPage = new companyHistoryPage();
    settingsPage settingsPage = new settingsPage();
    cashierLoginPage cashierLoginPage = new cashierLoginPage();
    /**
     * Creates new form initialView
     */
//    private ImageIcon marketIcon = new ImageIcon(this.getClass().getResource("/market"));
//    private JLabel img = new JLabel(marketIcon);
    public index() {
        initComponents();
       
        companyLoginPage.setGoodsPage(goodsPage);
        companyLoginPage.setIndex(index);
        companyLoginPage.setVisible(false);
        
        cashierLoginPage.setOrderPage(orderPage);
        cashierLoginPage.setIndex(index);
        cashierLoginPage.setVisible(false);
        
        registerPage.setIndex(index);
        registerPage.setLoginPage(companyLoginPage);
        registerPage.setVisible(false);
        
        goodsPage.setIndex(index);
        goodsPage.setOrderPage(orderPage);
        goodsPage.setHistoryPage(companyHistoyPage);
        goodsPage.setSettingsPage(settingsPage);
        goodsPage.setVisible(false);
        
        orderPage.setIndex(index);
        orderPage.setGoodsPage(goodsPage);
        orderPage.setHistoryPage(cashierHistoryPage);
        orderPage.setSettingsPage(settingsPage);
        orderPage.setVisible(false);
        
        cashierHistoryPage.setOrderPage(orderPage);
        cashierHistoryPage.setIndex(index);
        cashierHistoryPage.setVisible(false);
        
        companyHistoyPage.setIndex(index);
        companyHistoyPage.setGoodsPage(goodsPage);
        companyHistoyPage.setOrderPage(orderPage);
        companyHistoyPage.setSettingsPage(settingsPage);
        companyHistoyPage.setVisible(false);
        
        settingsPage.setIndex(index);
        settingsPage.setGoodsPage(goodsPage);
        settingsPage.setOrderPage(orderPage);
        settingsPage.setHistoryPage(companyHistoyPage);
        settingsPage.setVisible(false);

        add(registerPage);
        add(companyLoginPage);
        add(cashierLoginPage);
        add(cashierHistoryPage);
        add(goodsPage);
        add(orderPage);
        add(companyHistoyPage);
        add(settingsPage);
        
//        JLabel background;
//        this.setLayout(null);
//        setDefaultCloseOperation(EXIT_ON_CLOSE);
//        ImageIcon img = new ImageIcon(ClassLoader.getSystemResource("images/market.png"));
//        background = new JLabel("",img,JLabel.CENTER);
//        background.setBounds(0, 0, 1280, 832);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        index = new javax.swing.JPanel();
        registerBtn = new javax.swing.JButton();
        kasirSiginBtn = new javax.swing.JButton();
        companySiginBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        index.setBackground(new java.awt.Color(255, 255, 255));
        index.setPreferredSize(new java.awt.Dimension(360, 800));
        index.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerBtn.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setContentAreaFilled(false);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        index.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 525, -1, -1));

        kasirSiginBtn.setBackground(new java.awt.Color(33, 146, 255));
        kasirSiginBtn.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        kasirSiginBtn.setForeground(new java.awt.Color(255, 255, 255));
        kasirSiginBtn.setText("Sign in Seb Kasir");
        kasirSiginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 146, 255), 1, true));
        kasirSiginBtn.setContentAreaFilled(false);
        kasirSiginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasirSiginBtn.setMaximumSize(new java.awt.Dimension(331, 23));
        kasirSiginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasirSiginBtnActionPerformed(evt);
            }
        });
        index.add(kasirSiginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 470, 270, 40));

        companySiginBtn.setBackground(new java.awt.Color(33, 146, 255));
        companySiginBtn.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        companySiginBtn.setForeground(new java.awt.Color(255, 255, 255));
        companySiginBtn.setText("Sign in Seb Perusahaan");
        companySiginBtn.setBorder(null);
        companySiginBtn.setBorderPainted(false);
        companySiginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        companySiginBtn.setMaximumSize(new java.awt.Dimension(331, 23));
        companySiginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companySiginBtnActionPerformed(evt);
            }
        });
        index.add(companySiginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 415, 270, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        index.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 560, -1, 1));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 250, 252));
        jLabel1.setText("Cashierqu");
        jLabel1.setAlignmentX(100.0F);
        index.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 201, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("by using Cashierqu");
        index.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 339, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("increase the productivity of your store");
        index.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 303, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\img\\market.png")); // NOI18N
        jLabel3.setText("jLabel3");
        index.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1280, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(index, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companySiginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companySiginBtnActionPerformed
        index.setVisible(false);
        companyLoginPage.setVisible(true);
    }//GEN-LAST:event_companySiginBtnActionPerformed

    private void kasirSiginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasirSiginBtnActionPerformed
        index.setVisible(false);
        cashierLoginPage.setVisible(true);
    }//GEN-LAST:event_kasirSiginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        index.setVisible(false);
        registerPage.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                index jFrame = new index();
                jFrame.setVisible(true);
                jFrame.pack();
                jFrame.setSize(1280, 832);
                frame.center(jFrame);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton companySiginBtn;
    private javax.swing.JPanel index;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kasirSiginBtn;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
