/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.kasirapp.view;

import javax.swing.JPanel;
import com.mycompany.kasirapp.controller.controller;
import com.mycompany.kasirapp.model.Supermarket;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer SPIN
 */

public class registerPage extends javax.swing.JPanel {
    private JPanel index, loginPage;
    String pass,confirmPass;
    Supermarket supermarket = new Supermarket();
    /**
     * Creates new form Register
     */
    public registerPage() {
        initComponents();
        this.setSize(1280,832);
        popupAlert.setVisible(false);
        supermarketMaksAlert.setVisible(false);
        usernameMaksAlert.setVisible(false);
        passwordAlert.setVisible(false);
        registerBtn.setEnabled(false);
        minPassAlert.setVisible(false);
    }
    private boolean validasiData(Supermarket supermarket){
        boolean emptyNamaSupermarket = supermarket.getNamaSupermarket().equals("");
        boolean emptyUsername = supermarket.getNamaSupermarket().equals("");
        boolean emptyPass = supermarket.getPass().equals("");
        boolean emptyConfPass = supermarket.getConfirmPass().equals("");
        boolean maksNamaSupermarket = supermarket.getNamaSupermarket().length() > 15;
        boolean maksUsername = supermarket.getUsername().length() > 10;
        boolean minPass = supermarket.getPass().length() < 8;
        boolean passMatch = supermarket.getPass().equals(supermarket.getConfirmPass());
        
        registerBtn.setEnabled(!emptyNamaSupermarket && !emptyUsername && !emptyPass && !emptyConfPass);
        if(maksUsername == true){
            inputUsername.setText(supermarket.getUsername()
            .substring(0, supermarket.getUsername().length() - (supermarket.getUsername().length() - 10)));
        }
        if(maksNamaSupermarket == true){
            inputSupermarket.setText(supermarket.getNamaSupermarket()
            .substring(0, supermarket.getNamaSupermarket().length() - (supermarket.getNamaSupermarket().length() - 15)));
        }
        
        usernameMaksAlert.setVisible(maksUsername == true);
        supermarketMaksAlert.setVisible(maksNamaSupermarket == true);
        
        boolean namaSupermarket = !emptyNamaSupermarket && !maksNamaSupermarket;
        boolean username = !emptyUsername && !maksUsername;
        boolean pass = !emptyPass && passMatch && !minPass;
        boolean confPass = !emptyConfPass;
        return namaSupermarket && username && pass && confPass;
    }
    private void clearField(){
        inputSupermarket.setText("");
        inputUsername.setText("");
        inputPass.setText("");
        inputCorfirmPass.setText("");
    }
    public void setIndex(JPanel index) {
        this.index = index;
    }

    public void setLoginPage(JPanel loginPage) {
        this.loginPage = loginPage;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        popupAlert = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        okeBtn = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        inputCorfirmPass = new javax.swing.JPasswordField();
        confirmPassLabel = new javax.swing.JLabel();
        inputPass = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        usernameMaksAlert = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        supermarketMaksAlert = new javax.swing.JLabel();
        inputSupermarket = new javax.swing.JTextField();
        namaSpermarketLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        minPassAlert = new javax.swing.JLabel();
        passwordAlert = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 146, 255));
        setPreferredSize(new java.awt.Dimension(1000, 678));

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\arrow-back.png")); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\user.png")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        popupAlert.setBackground(new java.awt.Color(255, 255, 255));
        popupAlert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        popupAlert.setPreferredSize(new java.awt.Dimension(220, 120));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel2.setText("Sign up succes");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer SPIN\\OneDrive\\Dokumen\\NetBeansProjects\\kasirApp\\src\\main\\java\\com\\mycompany\\kasirapp\\icons\\succes.png")); // NOI18N

        okeBtn.setBackground(new java.awt.Color(33, 146, 255));
        okeBtn.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        okeBtn.setForeground(new java.awt.Color(255, 255, 255));
        okeBtn.setText("OK");
        okeBtn.setBorder(null);
        okeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okeBtn.setPreferredSize(new java.awt.Dimension(44, 18));
        okeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popupAlertLayout = new javax.swing.GroupLayout(popupAlert);
        popupAlert.setLayout(popupAlertLayout);
        popupAlertLayout.setHorizontalGroup(
            popupAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupAlertLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(72, 72, 72))
            .addGroup(popupAlertLayout.createSequentialGroup()
                .addGroup(popupAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupAlertLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3))
                    .addGroup(popupAlertLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(okeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        popupAlertLayout.setVerticalGroup(
            popupAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupAlertLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(okeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel1.add(popupAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        registerLabel.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        registerLabel.setText("Register");
        jPanel1.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 45, -1, -1));

        inputCorfirmPass.setPreferredSize(new java.awt.Dimension(331, 34));
        inputCorfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCorfirmPassFocusLost(evt);
            }
        });
        inputCorfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCorfirmPassKeyTyped(evt);
            }
        });
        jPanel1.add(inputCorfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 412, 331, 34));

        confirmPassLabel.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        confirmPassLabel.setText("Confirm Password");
        jPanel1.add(confirmPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 383, -1, -1));

        inputPass.setPreferredSize(new java.awt.Dimension(331, 34));
        inputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPassFocusLost(evt);
            }
        });
        inputPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPassKeyTyped(evt);
            }
        });
        jPanel1.add(inputPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 317, -1, -1));

        PasswordLabel.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 288, -1, -1));

        usernameMaksAlert.setForeground(new java.awt.Color(255, 0, 0));
        usernameMaksAlert.setText("Maksimum Karakter");
        jPanel1.add(usernameMaksAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 260, -1, -1));

        inputUsername.setPreferredSize(new java.awt.Dimension(331, 34));
        inputUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputUsernameKeyTyped(evt);
            }
        });
        jPanel1.add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 226, 331, 34));

        usernameLabel.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        usernameLabel.setText("Username");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 197, -1, -1));

        supermarketMaksAlert.setForeground(new java.awt.Color(255, 0, 0));
        supermarketMaksAlert.setText("Maksimum Karakter");
        jPanel1.add(supermarketMaksAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 169, -1, -1));

        inputSupermarket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputSupermarketKeyTyped(evt);
            }
        });
        jPanel1.add(inputSupermarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 129, 331, 34));

        namaSpermarketLabel.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        namaSpermarketLabel.setText("Nama Supermarket");
        jPanel1.add(namaSpermarketLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 100, -1, -1));

        registerBtn.setBackground(new java.awt.Color(33, 146, 255));
        registerBtn.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setBorder(null);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.setMaximumSize(new java.awt.Dimension(331, 23));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 484, 115, 34));

        minPassAlert.setForeground(new java.awt.Color(255, 0, 0));
        minPassAlert.setText("Minimum password : 8");
        jPanel1.add(minPassAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 357, -1, -1));

        passwordAlert.setForeground(new java.awt.Color(255, 0, 0));
        passwordAlert.setText("Password not match");
        jPanel1.add(passwordAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 452, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 395, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backBtn)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        index.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
            supermarket.setNamaSupermarket(inputSupermarket.getText());
            supermarket.setUsername(inputUsername.getText());
            supermarket.setPass(new String(inputPass.getPassword()));
            supermarket.setConfirmPass(new String(inputCorfirmPass.getPassword()));
            boolean passMatch = supermarket.getPass().equals(supermarket.getConfirmPass());
            boolean minPass = supermarket.getPass().length() < 8;
            
            if(supermarket.isRegistered(supermarket) == true){
                JOptionPane.showMessageDialog(null, "Username telah dipakai");
            }else{
                    if(validasiData(supermarket)){
                    supermarket.register();
                    this.setVisible(false);
                    this.loginPage.setVisible(true);
                    clearField();
                }
            }
        passwordAlert.setVisible(!passMatch); 
        minPassAlert.setVisible(minPass);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void inputSupermarketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSupermarketKeyTyped
        supermarket.setNamaSupermarket(inputSupermarket.getText());
        supermarket.setUsername(inputUsername.getText());
        supermarket.setPass(new String(inputPass.getPassword()));
        supermarket.setConfirmPass(new String(inputCorfirmPass.getPassword()));
        validasiData(supermarket);
    }//GEN-LAST:event_inputSupermarketKeyTyped

    private void inputUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputUsernameKeyTyped
        String username = inputUsername.getText();
        supermarket.setNamaSupermarket(inputSupermarket.getText());
        supermarket.setUsername(inputUsername.getText());
        supermarket.setPass(new String(inputPass.getPassword()));
        supermarket.setConfirmPass(new String(inputCorfirmPass.getPassword()));
        validasiData(supermarket);
    }//GEN-LAST:event_inputUsernameKeyTyped

    private void inputPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPassFocusLost
//        pass = new String(inputPass.getPassword());
    }//GEN-LAST:event_inputPassFocusLost

    private void inputPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPassKeyTyped
        supermarket.setNamaSupermarket(inputSupermarket.getText());
        supermarket.setUsername(inputUsername.getText());
        supermarket.setPass(new String(inputPass.getPassword()));
        supermarket.setConfirmPass(new String(inputCorfirmPass.getPassword()));
        validasiData(supermarket);
    }//GEN-LAST:event_inputPassKeyTyped

    private void inputCorfirmPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCorfirmPassKeyTyped
        supermarket.setNamaSupermarket(inputSupermarket.getText());
        supermarket.setUsername(inputUsername.getText());
        supermarket.setPass(new String(inputPass.getPassword()));
        supermarket.setConfirmPass(new String(inputCorfirmPass.getPassword()));
        validasiData(supermarket);
    }//GEN-LAST:event_inputCorfirmPassKeyTyped

    private void inputCorfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCorfirmPassFocusLost
//        confirmPass = new String(inputCorfirmPass.getPassword());
    }//GEN-LAST:event_inputCorfirmPassFocusLost

    private void okeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeBtnActionPerformed
        this.setVisible(false);
        this.loginPage.setVisible(true);
        this.popupAlert.setVisible(true);
    }//GEN-LAST:event_okeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JPasswordField inputCorfirmPass;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputSupermarket;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minPassAlert;
    private javax.swing.JLabel namaSpermarketLabel;
    private javax.swing.JButton okeBtn;
    private javax.swing.JLabel passwordAlert;
    private javax.swing.JPanel popupAlert;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel supermarketMaksAlert;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameMaksAlert;
    // End of variables declaration//GEN-END:variables
}
